const GAME_LIBRARY = [
  {
    id: 'mario64',
    title: 'Super Mario 64',
    image: 'assets/game-icons/mario64.svg',
    status: 'Runs great',
    url: 'games/mario64.html',
    color: 'var(--red)',
  },
  {
    id: 'e112',
    title: 'Eaglercraft 1.12',
    image: 'assets/game-icons/e112.svg',
    status: 'Experimental',
    special: true,
    wrapperUrl: 'https://cdn.jsdelivr.net/gh/PlanetDogeCodes/Eagletcraft-1.12@main/source%20file/egc1-12.xml',
    color: 'var(--purple)',
  },
  {
    id: 'dumLLM',
    title: 'dumLLM',
    image: 'assets/game-icons/dumLLM.svg',
    status: 'Stable-ish',
    url: 'games/dumLLM.html',
    color: 'var(--yellow)',
  },
  {
    id: 'badbrowser',
    title: 'Bad Browser',
    image: 'assets/game-icons/badbrowser.svg',
    status: 'Experimental',
    url: 'games/badbrowser.html',
    color: 'var(--teal)',
  },
  {
    id: 'mineKhan',
    title: 'MineKhan',
    image: 'assets/game-icons/mineKhan.svg',
    status: 'Runs great',
    url: 'games/mineKhan.html',
    color: 'var(--green)',
  },
  {
    id: 'karlson',
    title: 'Karlson',
    image: 'assets/game-icons/karlson.svg',
    status: 'Fast action',
    url: 'games/karlson.html',
    color: 'var(--red)',
  },
  {
    id: 'bss',
    title: 'Bee Swarm Simulator',
    image: 'assets/game-icons/bss.svg',
    status: 'Fun and stable',
    url: 'games/BSS.html',
    color: 'var(--yellow)',
  },
  {
    id: 'granny',
    title: 'Granny',
    image: 'assets/game-icons/granny.svg',
    status: 'Spooky',
    url: 'games/granny.html',
    color: 'var(--orange)',
  },
  {
    id: 'basketballlegends',
    title: 'Basketball Legends',
    image: 'assets/game-icons/basketballlegends.svg',
    status: 'Competitive',
    url: 'games/basketballlegends.html',
    color: 'var(--purple)',
  },
  {
    id: '1v1',
    title: '1v1',
    image: 'assets/game-icons/1v1.svg',
    status: 'Laggy on some machines',
    url: 'games/1v1.html',
    color: 'var(--pink)',
  },
  {
    id: 'donkeyKhan',
    title: 'Donkey Khan',
    image: 'assets/game-icons/donkeyKhan.svg',
    status: 'Classic fun',
    url: 'games/donkeyKhan.html',
    color: 'var(--orange)',
  },
  {
    id: 'genericPlatformer3d',
    title: 'Generic Platformer 3D',
    image: 'assets/game-icons/genericPlatformer3d.svg',
    status: 'Smooth',
    url: 'games/genericPlatformer3d.html',
    color: 'var(--green)',
  },
];
